version: '3'

services:
  mirth-connect:
    image: mirthconnect:latest
    ports:
      - "8080:8080"
      - "8443:8443"
      - "6661:6661"
      - "6662:6662"
    depends_on:
      - db
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mirthdb
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  db-data:
